/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainwin (void);
GtkWidget* create_progwin (void);
GtkWidget* create_progeditwin (void);
GtkWidget* create_progsavewin (void);
GtkWidget* create_settingswin (void);
GtkWidget* create_settingseditwin (void);
GtkWidget* create_debugwin (void);
GtkWidget* create_dlgWarnReset (void);
