/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

static GnomeUIInfo mnArkiv_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Inst\344llningar"),
    NULL,
    (gpointer) on_mnProperties_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_PREF,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Debugf\366nster"),
    NULL,
    (gpointer) on_mnDebugShow_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_INDEX,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Avsluta"),
    NULL,
    (gpointer) on_mnExitProgram_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_EXIT,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mnRotor_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Starta"),
    NULL,
    (gpointer) on_mnRotorStarta_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_TIMER,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Stoppa"),
    NULL,
    (gpointer) on_mnRotorStoppa_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_TIMER_STOP,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mnProgram_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Skapa nytt"),
    N_("Skapa ett nytt program"),
    (gpointer) on_mnProgramCreate_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_NEW,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("\304ndra"),
    N_("\304ndra i det valda programmet"),
    (gpointer) on_mnProgramModify_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_SRCHRPL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("K\366r"),
    NULL,
    (gpointer) on_mnProgramRun_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_FORWARD,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Pausa"),
    NULL,
    (gpointer) on_mnProgramPause_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_STOP,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("\305terst\344lla"),
    N_("B\366rja om fr\345n b\366rjan i programmet"),
    (gpointer) on_mnProgramReset_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_REFRESH,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mnControlGUI_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Grafisk"),
    N_("Styrning fr\345n GUI:et"),
    (gpointer) on_ctrlGui_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Manuell"),
    N_("Styrning mha fj\344rrkontroll"),
    (gpointer) on_ctrlMan_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mnControl_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_RADIOITEMS, NULL, NULL, mnControlGUI_uiinfo,
    NULL, NULL, GNOME_APP_PIXMAP_NONE, NULL, 0,
    (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo mbMain_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("Arkiv"),
    NULL,
    mnArkiv_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Rotor"),
    NULL,
    mnRotor_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Program"),
    NULL,
    mnProgram_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("Styrning"),
    NULL,
    mnControl_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_mainwin (void)
{
  GtkWidget *mainwin;
  GtkWidget *vbxBotten;
  GtkWidget *hbox6;
  GtkWidget *mbMain;
  GtkWidget *hbxBotten;
  GtkWidget *vbxA;
  GtkWidget *vbox15;
  GtkWidget *hbox7;
  GtkWidget *frmProgoptions;
  GtkWidget *omPrograms;
  GtkWidget *omPrograms_menu;
  GtkWidget *imgMain;
  GtkWidget *vbox9;
  GtkWidget *clInfo;
  GtkWidget *label11;
  GtkWidget *sbStatus;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  mainwin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (mainwin, "mainwin");
  gtk_object_set_data (GTK_OBJECT (mainwin), "mainwin", mainwin);
  gtk_container_set_border_width (GTK_CONTAINER (mainwin), 2);
  gtk_window_set_title (GTK_WINDOW (mainwin), _("Snogeholmskastaren"));

  vbxBotten = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbxBotten, "vbxBotten");
  gtk_widget_ref (vbxBotten);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "vbxBotten", vbxBotten,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbxBotten);
  gtk_container_add (GTK_CONTAINER (mainwin), vbxBotten);
  gtk_widget_set_usize (vbxBotten, 338, 300);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox6, "hbox6");
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbxBotten), hbox6, FALSE, FALSE, 0);

  mbMain = gtk_menu_bar_new ();
  gtk_widget_set_name (mbMain, "mbMain");
  gtk_widget_ref (mbMain);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mbMain", mbMain,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mbMain);
  gtk_box_pack_start (GTK_BOX (hbox6), mbMain, FALSE, FALSE, 0);
  gtk_widget_set_usize (mbMain, 340, -2);
  GTK_WIDGET_SET_FLAGS (mbMain, GTK_CAN_FOCUS);
  gtk_widget_add_accelerator (mbMain, "selection_done", accel_group,
                              GDK_m, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (mbMain, "activate_current", accel_group,
                              GDK_n, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (mbMain, "button_press_event", accel_group,
                              GDK_b, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);
  gnome_app_fill_menu (GTK_MENU_SHELL (mbMain), mbMain_uiinfo,
                       NULL, FALSE, 0);
  gtk_menu_bar_set_shadow_type (GTK_MENU_BAR (mbMain), GTK_SHADOW_ETCHED_IN);

  gtk_widget_set_name (mbMain_uiinfo[0].widget, "mnArkiv");
  gtk_widget_ref (mbMain_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnArkiv",
                            mbMain_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (mnArkiv_menu_uiinfo[0].widget, "mnProperties");
  gtk_widget_ref (mnArkiv_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnProperties",
                            mnArkiv_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (mnArkiv_menu_uiinfo[1].widget, "mnDebugShow");
  gtk_widget_ref (mnArkiv_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnDebugShow",
                            mnArkiv_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (mnArkiv_menu_uiinfo[2].widget, "mnExitProgram");
  gtk_widget_ref (mnArkiv_menu_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnExitProgram",
                            mnArkiv_menu_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (mbMain_uiinfo[1].widget, "mnRotor");
  gtk_widget_ref (mbMain_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnRotor",
                            mbMain_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (mnRotor_menu_uiinfo[0].widget, "mnRotorStarta");
  gtk_widget_ref (mnRotor_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnRotorStarta",
                            mnRotor_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (mnRotor_menu_uiinfo[1].widget, "mnRotorStoppa");
  gtk_widget_ref (mnRotor_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnRotorStoppa",
                            mnRotor_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_set_sensitive (mnRotor_menu_uiinfo[1].widget, FALSE);

  gtk_widget_set_name (mbMain_uiinfo[2].widget, "mnProgram");
  gtk_widget_ref (mbMain_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnProgram",
                            mbMain_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (mnProgram_menu_uiinfo[0].widget, "mnProgramCreate");
  gtk_widget_ref (mnProgram_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnProgramCreate",
                            mnProgram_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (mnProgram_menu_uiinfo[1].widget, "mnProgramModify");
  gtk_widget_ref (mnProgram_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnProgramModify",
                            mnProgram_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (mnProgram_menu_uiinfo[2].widget, "avskiljare2");
  gtk_widget_ref (mnProgram_menu_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "avskiljare2",
                            mnProgram_menu_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (mnProgram_menu_uiinfo[3].widget, "mnProgramRun");
  gtk_widget_ref (mnProgram_menu_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnProgramRun",
                            mnProgram_menu_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (mnProgram_menu_uiinfo[4].widget, "mnProgramPause");
  gtk_widget_ref (mnProgram_menu_uiinfo[4].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnProgramPause",
                            mnProgram_menu_uiinfo[4].widget,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_set_sensitive (mnProgram_menu_uiinfo[4].widget, FALSE);

  gtk_widget_set_name (mnProgram_menu_uiinfo[5].widget, "mnProgramReset");
  gtk_widget_ref (mnProgram_menu_uiinfo[5].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnProgramReset",
                            mnProgram_menu_uiinfo[5].widget,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_set_sensitive (mnProgram_menu_uiinfo[5].widget, FALSE);

  gtk_widget_set_name (mbMain_uiinfo[3].widget, "mnControl");
  gtk_widget_ref (mbMain_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnControl",
                            mbMain_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_set_name (mnControlGUI_uiinfo[0].widget, "mnControlGUI");
  gtk_widget_ref (mnControlGUI_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnControlGUI",
                            mnControlGUI_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (mnControlGUI_uiinfo[0].widget), TRUE);

  gtk_widget_set_name (mnControlGUI_uiinfo[1].widget, "mnControlManual");
  gtk_widget_ref (mnControlGUI_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "mnControlManual",
                            mnControlGUI_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  hbxBotten = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbxBotten, "hbxBotten");
  gtk_widget_ref (hbxBotten);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbxBotten", hbxBotten,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbxBotten);
  gtk_box_pack_start (GTK_BOX (vbxBotten), hbxBotten, TRUE, TRUE, 0);

  vbxA = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbxA, "vbxA");
  gtk_widget_ref (vbxA);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "vbxA", vbxA,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbxA);
  gtk_box_pack_start (GTK_BOX (hbxBotten), vbxA, TRUE, TRUE, 0);

  vbox15 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox15, "vbox15");
  gtk_widget_ref (vbox15);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "vbox15", vbox15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox15);
  gtk_box_pack_start (GTK_BOX (vbxA), vbox15, FALSE, FALSE, 0);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox7, "hbox7");
  gtk_widget_ref (hbox7);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox7", hbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox15), hbox7, FALSE, FALSE, 0);

  frmProgoptions = gtk_frame_new (_("Programval"));
  gtk_widget_set_name (frmProgoptions, "frmProgoptions");
  gtk_widget_ref (frmProgoptions);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "frmProgoptions", frmProgoptions,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frmProgoptions);
  gtk_box_pack_start (GTK_BOX (hbox7), frmProgoptions, FALSE, FALSE, 0);
  gtk_widget_set_usize (frmProgoptions, 128, -2);
  gtk_container_set_border_width (GTK_CONTAINER (frmProgoptions), 1);
  gtk_frame_set_shadow_type (GTK_FRAME (frmProgoptions), GTK_SHADOW_ETCHED_OUT);

  omPrograms = gtk_option_menu_new ();
  gtk_widget_set_name (omPrograms, "omPrograms");
  gtk_widget_ref (omPrograms);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "omPrograms", omPrograms,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (omPrograms);
  gtk_container_add (GTK_CONTAINER (frmProgoptions), omPrograms);
  gtk_widget_set_usize (omPrograms, 127, 25);
  gtk_tooltips_set_tip (tooltips, omPrograms, _("V\344lj program att k\366ra h\344r"), NULL);
  omPrograms_menu = gtk_menu_new ();
  gtk_option_menu_set_menu (GTK_OPTION_MENU (omPrograms), omPrograms_menu);

  imgMain = gtk_drawing_area_new ();
  gtk_widget_set_name (imgMain, "imgMain");
  gtk_widget_ref (imgMain);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "imgMain", imgMain,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (imgMain);
  gtk_box_pack_start (GTK_BOX (vbox15), imgMain, TRUE, TRUE, 0);
  gtk_widget_set_usize (imgMain, 100, 150);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox9, "vbox9");
  gtk_widget_ref (vbox9);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "vbox9", vbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (hbxBotten), vbox9, TRUE, TRUE, 0);

  clInfo = gtk_clist_new (1);
  gtk_widget_set_name (clInfo, "clInfo");
  gtk_widget_ref (clInfo);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "clInfo", clInfo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_box_pack_start (GTK_BOX (vbox9), clInfo, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (clInfo, GTK_CAN_FOCUS);
  gtk_clist_set_column_width (GTK_CLIST (clInfo), 0, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clInfo));

  label11 = gtk_label_new (_("Instruktioner"));
  gtk_widget_set_name (label11, "label11");
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_clist_set_column_widget (GTK_CLIST (clInfo), 0, label11);

  sbStatus = gtk_statusbar_new ();
  gtk_widget_set_name (sbStatus, "sbStatus");
  gtk_widget_ref (sbStatus);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "sbStatus", sbStatus,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sbStatus);
  gtk_box_pack_start (GTK_BOX (vbxBotten), sbStatus, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (mainwin), "destroy",
                      GTK_SIGNAL_FUNC (on_mainwin_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (imgMain), "expose_event",
                      GTK_SIGNAL_FUNC (on_imgMain_expose_event),
                      NULL);

  gtk_widget_grab_focus (omPrograms);
  gtk_object_set_data (GTK_OBJECT (mainwin), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (mainwin), accel_group);

  return mainwin;
}

GtkWidget*
create_progwin (void)
{
  GtkWidget *progwin;
  GtkWidget *vbox10;
  GtkWidget *vbox11;
  GtkWidget *scrolledwindow5;
  GtkWidget *clProgNew;
  GtkWidget *lblPwSkytt;
  GtkWidget *lblPwElev;
  GtkWidget *lblPwLerduvor;
  GtkWidget *hbox5;
  GtkWidget *vbox14;
  GtkWidget *btnProgsave;
  GtkWidget *frmProgGet;
  GtkWidget *omProgedit;
  GtkWidget *omProgedit_menu;
  GtkWidget *btnProgexit;
  GtkWidget *vbxProgwinSkyttinfo;
  GtkWidget *label26;
  GtkWidget *hbox8;
  GtkWidget *hseparator1;
  GtkWidget *lblProgeditName;
  GtkWidget *tblProgwinSkyttinfo;
  GtkWidget *lblSkytt1;
  GtkWidget *lblSkytt2;
  GtkWidget *lblSkytt3;
  GtkWidget *lblSkytt4;
  GtkWidget *lblSkytt5;
  GtkWidget *lblSkytt6;
  GtkWidget *lblSkytt7;
  GtkWidget *lblSkytt8;
  GtkWidget *label27;
  GtkWidget *label29;
  GtkWidget *label28;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label45;
  GtkWidget *lblSkyttA;
  GtkWidget *lblSkyttB;
  GtkWidget *lblSkyttC;
  GtkWidget *lblSkyttD;
  GtkWidget *lblSkyttE;
  GtkWidget *lblSkyttF;
  GtkWidget *lblSkyttG;
  GtkWidget *lblSkyttH;
  GtkWidget *sbProgedit;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  progwin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (progwin, "progwin");
  gtk_object_set_data (GTK_OBJECT (progwin), "progwin", progwin);
  gtk_window_set_title (GTK_WINDOW (progwin), _("-[programeditorn] nytt program-"));
  gtk_window_set_modal (GTK_WINDOW (progwin), TRUE);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox10, "vbox10");
  gtk_widget_ref (vbox10);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "vbox10", vbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox10);
  gtk_container_add (GTK_CONTAINER (progwin), vbox10);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox11, "vbox11");
  gtk_widget_ref (vbox11);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "vbox11", vbox11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (vbox10), vbox11, TRUE, TRUE, 0);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow5, "scrolledwindow5");
  gtk_widget_ref (scrolledwindow5);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "scrolledwindow5", scrolledwindow5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (vbox11), scrolledwindow5, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clProgNew = gtk_clist_new (3);
  gtk_widget_set_name (clProgNew, "clProgNew");
  gtk_widget_ref (clProgNew);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "clProgNew", clProgNew,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clProgNew);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), clProgNew);
  gtk_widget_set_usize (clProgNew, 390, 145);
  GTK_WIDGET_SET_FLAGS (clProgNew, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, clProgNew, _("H\344r ser du programmets instruktioner"), NULL);
  gtk_widget_add_accelerator (clProgNew, "select_row", accel_group,
                              GDK_space, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_clist_set_column_width (GTK_CLIST (clProgNew), 0, 97);
  gtk_clist_set_column_width (GTK_CLIST (clProgNew), 1, 98);
  gtk_clist_set_column_width (GTK_CLIST (clProgNew), 2, 128);
  gtk_clist_column_titles_show (GTK_CLIST (clProgNew));
  gtk_clist_set_shadow_type (GTK_CLIST (clProgNew), GTK_SHADOW_ETCHED_OUT);

  lblPwSkytt = gtk_label_new (_("Skytt"));
  gtk_widget_set_name (lblPwSkytt, "lblPwSkytt");
  gtk_widget_ref (lblPwSkytt);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblPwSkytt", lblPwSkytt,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblPwSkytt);
  gtk_clist_set_column_widget (GTK_CLIST (clProgNew), 0, lblPwSkytt);
  gtk_label_set_justify (GTK_LABEL (lblPwSkytt), GTK_JUSTIFY_LEFT);

  lblPwElev = gtk_label_new (_("Elevation"));
  gtk_widget_set_name (lblPwElev, "lblPwElev");
  gtk_widget_ref (lblPwElev);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblPwElev", lblPwElev,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblPwElev);
  gtk_clist_set_column_widget (GTK_CLIST (clProgNew), 1, lblPwElev);

  lblPwLerduvor = gtk_label_new (_("Lerduvor"));
  gtk_widget_set_name (lblPwLerduvor, "lblPwLerduvor");
  gtk_widget_ref (lblPwLerduvor);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblPwLerduvor", lblPwLerduvor,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblPwLerduvor);
  gtk_clist_set_column_widget (GTK_CLIST (clProgNew), 2, lblPwLerduvor);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox5, "hbox5");
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox5, TRUE, TRUE, 0);

  vbox14 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox14, "vbox14");
  gtk_widget_ref (vbox14);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "vbox14", vbox14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox14);
  gtk_box_pack_start (GTK_BOX (hbox5), vbox14, TRUE, TRUE, 0);

  btnProgsave = gtk_button_new_with_label (_("Spara program"));
  gtk_widget_set_name (btnProgsave, "btnProgsave");
  gtk_widget_ref (btnProgsave);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "btnProgsave", btnProgsave,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnProgsave);
  gtk_box_pack_start (GTK_BOX (vbox14), btnProgsave, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (btnProgsave), 5);

  frmProgGet = gtk_frame_new (_("H\344mta program"));
  gtk_widget_set_name (frmProgGet, "frmProgGet");
  gtk_widget_ref (frmProgGet);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "frmProgGet", frmProgGet,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frmProgGet);
  gtk_box_pack_start (GTK_BOX (vbox14), frmProgGet, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frmProgGet), 5);

  omProgedit = gtk_option_menu_new ();
  gtk_widget_set_name (omProgedit, "omProgedit");
  gtk_widget_ref (omProgedit);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "omProgedit", omProgedit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (omProgedit);
  gtk_container_add (GTK_CONTAINER (frmProgGet), omProgedit);
  gtk_tooltips_set_tip (tooltips, omProgedit, _("Program att ladda in i editorn"), NULL);
  omProgedit_menu = gtk_menu_new ();
  gtk_option_menu_set_menu (GTK_OPTION_MENU (omProgedit), omProgedit_menu);

  btnProgexit = gtk_button_new_with_label (_("St\344ng editor"));
  gtk_widget_set_name (btnProgexit, "btnProgexit");
  gtk_widget_ref (btnProgexit);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "btnProgexit", btnProgexit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnProgexit);
  gtk_box_pack_start (GTK_BOX (vbox14), btnProgexit, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (btnProgexit), 5);

  vbxProgwinSkyttinfo = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbxProgwinSkyttinfo, "vbxProgwinSkyttinfo");
  gtk_widget_ref (vbxProgwinSkyttinfo);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "vbxProgwinSkyttinfo", vbxProgwinSkyttinfo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbxProgwinSkyttinfo);
  gtk_box_pack_start (GTK_BOX (hbox5), vbxProgwinSkyttinfo, TRUE, TRUE, 0);
  gtk_widget_set_usize (vbxProgwinSkyttinfo, -2, 10);
  gtk_container_set_border_width (GTK_CONTAINER (vbxProgwinSkyttinfo), 5);

  label26 = gtk_label_new (_("Totalt antal utdelade lerduvor f\366r varje skytt:"));
  gtk_widget_set_name (label26, "label26");
  gtk_widget_ref (label26);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label26", label26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (vbxProgwinSkyttinfo), label26, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0.01, 0.5);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox8, "hbox8");
  gtk_widget_ref (hbox8);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "hbox8", hbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbxProgwinSkyttinfo), hbox8, TRUE, TRUE, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator1, "hseparator1");
  gtk_widget_ref (hseparator1);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "hseparator1", hseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (hbox8), hseparator1, TRUE, TRUE, 0);

  lblProgeditName = gtk_label_new ("");
  gtk_widget_set_name (lblProgeditName, "lblProgeditName");
  gtk_widget_ref (lblProgeditName);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblProgeditName", lblProgeditName,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_box_pack_start (GTK_BOX (hbox8), lblProgeditName, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (lblProgeditName, FALSE);

  tblProgwinSkyttinfo = gtk_table_new (4, 8, FALSE);
  gtk_widget_set_name (tblProgwinSkyttinfo, "tblProgwinSkyttinfo");
  gtk_widget_ref (tblProgwinSkyttinfo);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "tblProgwinSkyttinfo", tblProgwinSkyttinfo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tblProgwinSkyttinfo);
  gtk_box_pack_start (GTK_BOX (vbxProgwinSkyttinfo), tblProgwinSkyttinfo, TRUE, TRUE, 0);

  lblSkytt1 = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkytt1, "lblSkytt1");
  gtk_widget_ref (lblSkytt1);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkytt1", lblSkytt1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkytt1);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkytt1, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkytt1), 0, 0.5);

  lblSkytt2 = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkytt2, "lblSkytt2");
  gtk_widget_ref (lblSkytt2);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkytt2", lblSkytt2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkytt2);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkytt2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkytt2), 0, 0.5);

  lblSkytt3 = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkytt3, "lblSkytt3");
  gtk_widget_ref (lblSkytt3);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkytt3", lblSkytt3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkytt3);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkytt3, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkytt3), 0, 0.5);

  lblSkytt4 = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkytt4, "lblSkytt4");
  gtk_widget_ref (lblSkytt4);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkytt4", lblSkytt4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkytt4);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkytt4, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkytt4), 0, 0.5);

  lblSkytt5 = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkytt5, "lblSkytt5");
  gtk_widget_ref (lblSkytt5);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkytt5", lblSkytt5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkytt5);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkytt5, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkytt5), 0, 0.5);

  lblSkytt6 = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkytt6, "lblSkytt6");
  gtk_widget_ref (lblSkytt6);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkytt6", lblSkytt6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkytt6);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkytt6, 5, 6, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkytt6), 0, 0.5);

  lblSkytt7 = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkytt7, "lblSkytt7");
  gtk_widget_ref (lblSkytt7);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkytt7", lblSkytt7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkytt7);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkytt7, 6, 7, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkytt7), 0, 0.5);

  lblSkytt8 = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkytt8, "lblSkytt8");
  gtk_widget_ref (lblSkytt8);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkytt8", lblSkytt8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkytt8);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkytt8, 7, 8, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkytt8), 0, 0.5);

  label27 = gtk_label_new (_("[1]"));
  gtk_widget_set_name (label27, "label27");
  gtk_widget_ref (label27);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label27", label27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label27, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  label29 = gtk_label_new (_("[3]"));
  gtk_widget_set_name (label29, "label29");
  gtk_widget_ref (label29);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label29", label29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label29, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  label28 = gtk_label_new (_("[2]"));
  gtk_widget_set_name (label28, "label28");
  gtk_widget_ref (label28);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label28", label28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label28, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  label30 = gtk_label_new (_("[4]"));
  gtk_widget_set_name (label30, "label30");
  gtk_widget_ref (label30);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label30", label30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label30, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  label31 = gtk_label_new (_("[5]"));
  gtk_widget_set_name (label31, "label31");
  gtk_widget_ref (label31);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label31", label31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label31, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  label32 = gtk_label_new (_("[6]"));
  gtk_widget_set_name (label32, "label32");
  gtk_widget_ref (label32);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label32", label32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label32);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label32, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label32), 0, 0.5);

  label33 = gtk_label_new (_("[7]"));
  gtk_widget_set_name (label33, "label33");
  gtk_widget_ref (label33);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label33", label33,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label33);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label33, 6, 7, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label33), 0, 0.5);

  label34 = gtk_label_new (_("[8]"));
  gtk_widget_set_name (label34, "label34");
  gtk_widget_ref (label34);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label34", label34,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label34);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label34, 7, 8, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label34), 0, 0.5);

  label35 = gtk_label_new (_("[A]"));
  gtk_widget_set_name (label35, "label35");
  gtk_widget_ref (label35);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label35", label35,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label35);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label35, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label35), 0, 0.5);

  label36 = gtk_label_new (_("[B]"));
  gtk_widget_set_name (label36, "label36");
  gtk_widget_ref (label36);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label36", label36,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label36);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label36, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label36), 0, 0.5);

  label37 = gtk_label_new (_("[C]"));
  gtk_widget_set_name (label37, "label37");
  gtk_widget_ref (label37);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label37", label37,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label37);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label37, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label37), 0, 0.5);

  label38 = gtk_label_new (_("[D]"));
  gtk_widget_set_name (label38, "label38");
  gtk_widget_ref (label38);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label38", label38,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label38);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label38, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label38), 0, 0.5);

  label39 = gtk_label_new (_("[E]"));
  gtk_widget_set_name (label39, "label39");
  gtk_widget_ref (label39);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label39", label39,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label39);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label39, 4, 5, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label39), 0, 0.5);

  label40 = gtk_label_new (_("[F]"));
  gtk_widget_set_name (label40, "label40");
  gtk_widget_ref (label40);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label40", label40,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label40);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label40, 5, 6, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label40), 0, 0.5);

  label41 = gtk_label_new (_("[G]"));
  gtk_widget_set_name (label41, "label41");
  gtk_widget_ref (label41);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label41", label41,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label41);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label41, 6, 7, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label41), 0, 0.5);

  label45 = gtk_label_new (_("[H]"));
  gtk_widget_set_name (label45, "label45");
  gtk_widget_ref (label45);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "label45", label45,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label45);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), label45, 7, 8, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label45), 0, 0.5);

  lblSkyttA = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkyttA, "lblSkyttA");
  gtk_widget_ref (lblSkyttA);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkyttA", lblSkyttA,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkyttA);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkyttA, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkyttA), 0, 0.5);

  lblSkyttB = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkyttB, "lblSkyttB");
  gtk_widget_ref (lblSkyttB);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkyttB", lblSkyttB,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkyttB);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkyttB, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkyttB), 0, 0.5);

  lblSkyttC = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkyttC, "lblSkyttC");
  gtk_widget_ref (lblSkyttC);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkyttC", lblSkyttC,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkyttC);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkyttC, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkyttC), 0, 0.5);

  lblSkyttD = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkyttD, "lblSkyttD");
  gtk_widget_ref (lblSkyttD);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkyttD", lblSkyttD,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkyttD);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkyttD, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkyttD), 0, 0.5);

  lblSkyttE = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkyttE, "lblSkyttE");
  gtk_widget_ref (lblSkyttE);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkyttE", lblSkyttE,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkyttE);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkyttE, 4, 5, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkyttE), 0, 0.5);

  lblSkyttF = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkyttF, "lblSkyttF");
  gtk_widget_ref (lblSkyttF);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkyttF", lblSkyttF,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkyttF);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkyttF, 5, 6, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkyttF), 0, 0.5);

  lblSkyttG = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkyttG, "lblSkyttG");
  gtk_widget_ref (lblSkyttG);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkyttG", lblSkyttG,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkyttG);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkyttG, 6, 7, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkyttG), 0, 0.5);

  lblSkyttH = gtk_label_new (_("0"));
  gtk_widget_set_name (lblSkyttH, "lblSkyttH");
  gtk_widget_ref (lblSkyttH);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "lblSkyttH", lblSkyttH,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblSkyttH);
  gtk_table_attach (GTK_TABLE (tblProgwinSkyttinfo), lblSkyttH, 7, 8, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblSkyttH), 0, 0.5);

  sbProgedit = gtk_statusbar_new ();
  gtk_widget_set_name (sbProgedit, "sbProgedit");
  gtk_widget_ref (sbProgedit);
  gtk_object_set_data_full (GTK_OBJECT (progwin), "sbProgedit", sbProgedit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sbProgedit);
  gtk_box_pack_start (GTK_BOX (vbox10), sbProgedit, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (progwin), "delete_event",
                      GTK_SIGNAL_FUNC (on_progwin_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clProgNew), "select_row",
                      GTK_SIGNAL_FUNC (on_clProgNew_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnProgsave), "clicked",
                      GTK_SIGNAL_FUNC (on_btnProgsave_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnProgexit), "clicked",
                      GTK_SIGNAL_FUNC (on_btnProgexit_clicked),
                      NULL);

  gtk_widget_grab_focus (clProgNew);
  gtk_widget_grab_default (clProgNew);
  gtk_object_set_data (GTK_OBJECT (progwin), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (progwin), accel_group);

  return progwin;
}

GtkWidget*
create_progeditwin (void)
{
  GtkWidget *progeditwin;
  GtkWidget *layout1;
  GtkWidget *btnProgEditOk;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *lbl_ID;
  GtkWidget *omSkytt;
  GtkWidget *omSkytt_menu;
  GtkWidget *glade_menuitem;
  GtkObject *sbDuvor_adj;
  GtkWidget *sbDuvor;
  GtkWidget *omElev;
  GtkWidget *omElev_menu;
  GtkWidget *btnProgEditCancel;
  GtkWidget *btnProgEditDelete;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  progeditwin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (progeditwin, "progeditwin");
  gtk_object_set_data (GTK_OBJECT (progeditwin), "progeditwin", progeditwin);
  gtk_window_set_title (GTK_WINDOW (progeditwin), _("-\304ndra instruktion-"));
  gtk_window_set_position (GTK_WINDOW (progeditwin), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (progeditwin), TRUE);

  layout1 = gtk_layout_new (NULL, NULL);
  gtk_widget_set_name (layout1, "layout1");
  gtk_widget_ref (layout1);
  gtk_object_set_data_full (GTK_OBJECT (progeditwin), "layout1", layout1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (layout1);
  gtk_container_add (GTK_CONTAINER (progeditwin), layout1);
  gtk_widget_set_usize (layout1, 250, 110);
  gtk_layout_set_size (GTK_LAYOUT (layout1), 220, 106);
  GTK_ADJUSTMENT (GTK_LAYOUT (layout1)->hadjustment)->step_increment = 5;
  GTK_ADJUSTMENT (GTK_LAYOUT (layout1)->vadjustment)->step_increment = 5;

  btnProgEditOk = gnome_stock_button (GNOME_STOCK_BUTTON_OK);
  gtk_widget_set_name (btnProgEditOk, "btnProgEditOk");
  gtk_widget_ref (btnProgEditOk);
  gtk_object_set_data_full (GTK_OBJECT (progeditwin), "btnProgEditOk", btnProgEditOk,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnProgEditOk);
  gtk_layout_put (GTK_LAYOUT (layout1), btnProgEditOk, 160, 10);
  gtk_widget_set_usize (btnProgEditOk, 74, 24);
  gtk_widget_add_accelerator (btnProgEditOk, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  label4 = gtk_label_new (_("Skytt"));
  gtk_widget_set_name (label4, "label4");
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (progeditwin), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_layout_put (GTK_LAYOUT (layout1), label4, 8, 14);
  gtk_widget_set_usize (label4, 40, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 1.49012e-08, 0.5);

  label5 = gtk_label_new (_("Vinkel"));
  gtk_widget_set_name (label5, "label5");
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (progeditwin), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_layout_put (GTK_LAYOUT (layout1), label5, 8, 46);
  gtk_widget_set_usize (label5, 48, 16);
  gtk_misc_set_alignment (GTK_MISC (label5), 7.45058e-09, 0.5);

  label6 = gtk_label_new (_("Lerduvor"));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (progeditwin), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_layout_put (GTK_LAYOUT (layout1), label6, 8, 77);
  gtk_widget_set_usize (label6, 54, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 7.45058e-09, 0.5);

  lbl_ID = gtk_label_new ("");
  gtk_label_parse_uline (GTK_LABEL (lbl_ID),
                         _("osynlig [lbl_ID]"));
  gtk_widget_set_name (lbl_ID, "lbl_ID");
  gtk_widget_ref (lbl_ID);
  gtk_object_set_data_full (GTK_OBJECT (progeditwin), "lbl_ID", lbl_ID,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_layout_put (GTK_LAYOUT (layout1), lbl_ID, 0, 96);
  gtk_widget_set_usize (lbl_ID, 80, 16);
  gtk_widget_set_sensitive (lbl_ID, FALSE);

  omSkytt = gtk_option_menu_new ();
  gtk_widget_set_name (omSkytt, "omSkytt");
  gtk_widget_ref (omSkytt);
  gtk_object_set_data_full (GTK_OBJECT (progeditwin), "omSkytt", omSkytt,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (omSkytt);
  gtk_layout_put (GTK_LAYOUT (layout1), omSkytt, 56, 10);
  gtk_widget_set_usize (omSkytt, 80, 24);
  GTK_WIDGET_SET_FLAGS (omSkytt, GTK_CAN_DEFAULT);
  omSkytt_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("1"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("2"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("3"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("4"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("5"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("6"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("7"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("8"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("A"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("B"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("C"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("D"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("E"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("F"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("G"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("H"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Paustid"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omSkytt_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (omSkytt), omSkytt_menu);

  sbDuvor_adj = gtk_adjustment_new (1, 1, 10000, 1, 10, 10);
  sbDuvor = gtk_spin_button_new (GTK_ADJUSTMENT (sbDuvor_adj), 1, 0);
  gtk_widget_set_name (sbDuvor, "sbDuvor");
  gtk_widget_ref (sbDuvor);
  gtk_object_set_data_full (GTK_OBJECT (progeditwin), "sbDuvor", sbDuvor,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sbDuvor);
  gtk_layout_put (GTK_LAYOUT (layout1), sbDuvor, 90, 74);
  gtk_widget_set_usize (sbDuvor, 49, 24);
  GTK_WIDGET_SET_FLAGS (sbDuvor, GTK_CAN_DEFAULT);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (sbDuvor), TRUE);

  omElev = gtk_option_menu_new ();
  gtk_widget_set_name (omElev, "omElev");
  gtk_widget_ref (omElev);
  gtk_object_set_data_full (GTK_OBJECT (progeditwin), "omElev", omElev,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (omElev);
  gtk_layout_put (GTK_LAYOUT (layout1), omElev, 56, 42);
  gtk_widget_set_usize (omElev, 80, 24);
  GTK_WIDGET_SET_FLAGS (omElev, GTK_CAN_DEFAULT);
  omElev_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("L\345g"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omElev_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Mitten"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omElev_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("H\366g"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (omElev_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (omElev), omElev_menu);

  btnProgEditCancel = gnome_stock_button (GNOME_STOCK_BUTTON_CANCEL);
  gtk_widget_set_name (btnProgEditCancel, "btnProgEditCancel");
  gtk_widget_ref (btnProgEditCancel);
  gtk_object_set_data_full (GTK_OBJECT (progeditwin), "btnProgEditCancel", btnProgEditCancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnProgEditCancel);
  gtk_layout_put (GTK_LAYOUT (layout1), btnProgEditCancel, 160, 42);
  gtk_widget_set_usize (btnProgEditCancel, 73, 24);

  btnProgEditDelete = gtk_button_new_with_label (_("Ta bort"));
  gtk_widget_set_name (btnProgEditDelete, "btnProgEditDelete");
  gtk_widget_ref (btnProgEditDelete);
  gtk_object_set_data_full (GTK_OBJECT (progeditwin), "btnProgEditDelete", btnProgEditDelete,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnProgEditDelete);
  gtk_layout_put (GTK_LAYOUT (layout1), btnProgEditDelete, 160, 74);
  gtk_widget_set_usize (btnProgEditDelete, 74, 24);
  gtk_button_set_relief (GTK_BUTTON (btnProgEditDelete), GTK_RELIEF_HALF);

  gtk_signal_connect (GTK_OBJECT (progeditwin), "delete_event",
                      GTK_SIGNAL_FUNC (on_progeditwin_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnProgEditOk), "clicked",
                      GTK_SIGNAL_FUNC (on_btnProgEditButtons_clicked),
                      (gpointer)1);
  gtk_signal_connect (GTK_OBJECT (btnProgEditCancel), "clicked",
                      GTK_SIGNAL_FUNC (on_btnProgEditButtons_clicked),
                      (gpointer)0);
  gtk_signal_connect (GTK_OBJECT (btnProgEditDelete), "clicked",
                      GTK_SIGNAL_FUNC (on_btnProgEditButtons_clicked),
                      (gpointer)2);

  gtk_widget_grab_focus (btnProgEditOk);
  gtk_widget_grab_default (btnProgEditOk);
  gtk_window_add_accel_group (GTK_WINDOW (progeditwin), accel_group);

  return progeditwin;
}

GtkWidget*
create_progsavewin (void)
{
  GtkWidget *progsavewin;
  GtkWidget *scrolledwindow2;
  GtkWidget *layout2;
  GtkWidget *enProgname;
  GtkWidget *btnProgsavename;
  GtkWidget *label7;

  progsavewin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (progsavewin, "progsavewin");
  gtk_object_set_data (GTK_OBJECT (progsavewin), "progsavewin", progsavewin);
  gtk_window_set_title (GTK_WINDOW (progsavewin), _("Spara program"));
  gtk_window_set_position (GTK_WINDOW (progsavewin), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (progsavewin), TRUE);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (progsavewin), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (progsavewin), scrolledwindow2);
  gtk_widget_set_usize (scrolledwindow2, 190, 90);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_NEVER, GTK_POLICY_NEVER);

  layout2 = gtk_layout_new (NULL, NULL);
  gtk_widget_set_name (layout2, "layout2");
  gtk_widget_ref (layout2);
  gtk_object_set_data_full (GTK_OBJECT (progsavewin), "layout2", layout2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (layout2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), layout2);
  gtk_layout_set_size (GTK_LAYOUT (layout2), 200, 100);
  GTK_ADJUSTMENT (GTK_LAYOUT (layout2)->hadjustment)->step_increment = 10;
  GTK_ADJUSTMENT (GTK_LAYOUT (layout2)->vadjustment)->step_increment = 10;

  enProgname = gtk_entry_new ();
  gtk_widget_set_name (enProgname, "enProgname");
  gtk_widget_ref (enProgname);
  gtk_object_set_data_full (GTK_OBJECT (progsavewin), "enProgname", enProgname,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (enProgname);
  gtk_layout_put (GTK_LAYOUT (layout2), enProgname, 16, 24);
  gtk_widget_set_usize (enProgname, 158, 22);

  btnProgsavename = gnome_stock_button (GNOME_STOCK_BUTTON_OK);
  gtk_widget_set_name (btnProgsavename, "btnProgsavename");
  gtk_widget_ref (btnProgsavename);
  gtk_object_set_data_full (GTK_OBJECT (progsavewin), "btnProgsavename", btnProgsavename,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnProgsavename);
  gtk_layout_put (GTK_LAYOUT (layout2), btnProgsavename, 56, 48);
  gtk_widget_set_usize (btnProgsavename, 80, 37);
  GTK_WIDGET_SET_FLAGS (btnProgsavename, GTK_CAN_DEFAULT);

  label7 = gtk_label_new (_("V\344lj ett namn p\345 programmet"));
  gtk_widget_set_name (label7, "label7");
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (progsavewin), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_layout_put (GTK_LAYOUT (layout2), label7, 10, 8);
  gtk_widget_set_usize (label7, 168, 16);

  gtk_signal_connect (GTK_OBJECT (btnProgsavename), "clicked",
                      GTK_SIGNAL_FUNC (on_btnProgsavename_clicked),
                      NULL);

  gtk_widget_grab_focus (enProgname);
  gtk_widget_grab_default (btnProgsavename);
  return progsavewin;
}

GtkWidget*
create_settingswin (void)
{
  GtkWidget *settingswin;
  GtkWidget *scrolledwindow3;
  GtkWidget *viewport1;
  GtkWidget *vbox6;
  GtkWidget *hbox3;
  GtkWidget *label20;
  GtkWidget *vseparator2;
  GtkWidget *vbox8;
  guint btnSettingsReset_key;
  GtkWidget *btnSettingsReset;
  guint btnSettingsExit_key;
  GtkWidget *btnSettingsExit;
  GtkWidget *clSettings;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  settingswin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (settingswin, "settingswin");
  gtk_object_set_data (GTK_OBJECT (settingswin), "settingswin", settingswin);
  gtk_window_set_title (GTK_WINDOW (settingswin), _("Inst\344llningar"));

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow3, "scrolledwindow3");
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (settingswin), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (settingswin), scrolledwindow3);
  gtk_widget_set_usize (scrolledwindow3, 400, 250);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_NEVER);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (viewport1, "viewport1");
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (settingswin), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), viewport1);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox6, "vbox6");
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (settingswin), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (viewport1), vbox6);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (settingswin), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox3, FALSE, TRUE, 0);

  label20 = gtk_label_new (_("H\344r kan du st\344lla in olika variabler som programmet anv\344nder.\n\304ndringarna kr\344ver att programmet startas om innan de tar effekt."));
  gtk_widget_set_name (label20, "label20");
  gtk_widget_ref (label20);
  gtk_object_set_data_full (GTK_OBJECT (settingswin), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox3), label20, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label20), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label20), TRUE);
  gtk_misc_set_padding (GTK_MISC (label20), 6, 0);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_set_name (vseparator2, "vseparator2");
  gtk_widget_ref (vseparator2);
  gtk_object_set_data_full (GTK_OBJECT (settingswin), "vseparator2", vseparator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vseparator2);
  gtk_box_pack_start (GTK_BOX (hbox3), vseparator2, TRUE, TRUE, 0);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox8, "vbox8");
  gtk_widget_ref (vbox8);
  gtk_object_set_data_full (GTK_OBJECT (settingswin), "vbox8", vbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (hbox3), vbox8, TRUE, TRUE, 0);

  btnSettingsReset = gtk_button_new_with_label ("");
  btnSettingsReset_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (btnSettingsReset)->child),
                                   _("S\344tt \ns_tandardv\344rden"));
  gtk_widget_add_accelerator (btnSettingsReset, "clicked", accel_group,
                              btnSettingsReset_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_set_name (btnSettingsReset, "btnSettingsReset");
  gtk_widget_ref (btnSettingsReset);
  gtk_object_set_data_full (GTK_OBJECT (settingswin), "btnSettingsReset", btnSettingsReset,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnSettingsReset);
  gtk_box_pack_start (GTK_BOX (vbox8), btnSettingsReset, FALSE, FALSE, 0);
  gtk_widget_add_accelerator (btnSettingsReset, "clicked", accel_group,
                              GDK_t, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  btnSettingsExit = gtk_button_new_with_label ("");
  btnSettingsExit_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (btnSettingsExit)->child),
                                   _("_St\344ng"));
  gtk_widget_add_accelerator (btnSettingsExit, "clicked", accel_group,
                              btnSettingsExit_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_set_name (btnSettingsExit, "btnSettingsExit");
  gtk_widget_ref (btnSettingsExit);
  gtk_object_set_data_full (GTK_OBJECT (settingswin), "btnSettingsExit", btnSettingsExit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnSettingsExit);
  gtk_box_pack_start (GTK_BOX (vbox8), btnSettingsExit, FALSE, FALSE, 0);
  gtk_widget_add_accelerator (btnSettingsExit, "clicked", accel_group,
                              GDK_s, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  clSettings = gtk_clist_new (2);
  gtk_widget_set_name (clSettings, "clSettings");
  gtk_widget_ref (clSettings);
  gtk_object_set_data_full (GTK_OBJECT (settingswin), "clSettings", clSettings,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clSettings);
  gtk_box_pack_start (GTK_BOX (vbox6), clSettings, TRUE, TRUE, 0);
  gtk_widget_add_accelerator (clSettings, "select_row", accel_group,
                              GDK_space, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_clist_set_column_width (GTK_CLIST (clSettings), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clSettings), 1, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clSettings));
  gtk_clist_set_shadow_type (GTK_CLIST (clSettings), GTK_SHADOW_ETCHED_OUT);

  label18 = gtk_label_new (_("Namn"));
  gtk_widget_set_name (label18, "label18");
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (settingswin), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_clist_set_column_widget (GTK_CLIST (clSettings), 0, label18);

  label19 = gtk_label_new (_("V\344rde"));
  gtk_widget_set_name (label19, "label19");
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (settingswin), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_clist_set_column_widget (GTK_CLIST (clSettings), 1, label19);

  gtk_signal_connect (GTK_OBJECT (settingswin), "delete_event",
                      GTK_SIGNAL_FUNC (on_settingswin_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnSettingsReset), "clicked",
                      GTK_SIGNAL_FUNC (on_btnSettingsReset_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnSettingsExit), "clicked",
                      GTK_SIGNAL_FUNC (on_btnSettingsExit_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clSettings), "select_row",
                      GTK_SIGNAL_FUNC (on_clSettings_select_row),
                      NULL);

  gtk_widget_grab_focus (clSettings);
  gtk_window_add_accel_group (GTK_WINDOW (settingswin), accel_group);

  return settingswin;
}

GtkWidget*
create_settingseditwin (void)
{
  GtkWidget *settingseditwin;
  GtkWidget *vbox7;
  GtkWidget *table2;
  GtkWidget *enName;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *enValue;
  GtkWidget *hidRow;
  GtkWidget *btnSettingsEditOK;

  settingseditwin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (settingseditwin, "settingseditwin");
  gtk_object_set_data (GTK_OBJECT (settingseditwin), "settingseditwin", settingseditwin);
  gtk_window_set_title (GTK_WINDOW (settingseditwin), _("Variabel\344ndring"));
  gtk_window_set_position (GTK_WINDOW (settingseditwin), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (settingseditwin), TRUE);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox7, "vbox7");
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (settingseditwin), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (settingseditwin), vbox7);
  gtk_widget_set_usize (vbox7, 340, 66);

  table2 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table2, "table2");
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (settingseditwin), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox7), table2, FALSE, TRUE, 0);

  enName = gtk_entry_new ();
  gtk_widget_set_name (enName, "enName");
  gtk_widget_ref (enName);
  gtk_object_set_data_full (GTK_OBJECT (settingseditwin), "enName", enName,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (enName);
  gtk_table_attach (GTK_TABLE (table2), enName, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (enName, 90, 25);

  label21 = gtk_label_new (_("Namn"));
  gtk_widget_set_name (label21, "label21");
  gtk_widget_ref (label21);
  gtk_object_set_data_full (GTK_OBJECT (settingseditwin), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table2), label21, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  label22 = gtk_label_new (_("V\344rde"));
  gtk_widget_set_name (label22, "label22");
  gtk_widget_ref (label22);
  gtk_object_set_data_full (GTK_OBJECT (settingseditwin), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table2), label22, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  enValue = gtk_entry_new ();
  gtk_widget_set_name (enValue, "enValue");
  gtk_widget_ref (enValue);
  gtk_object_set_data_full (GTK_OBJECT (settingseditwin), "enValue", enValue,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (enValue);
  gtk_table_attach (GTK_TABLE (table2), enValue, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (enValue, 90, 25);

  hidRow = gtk_label_new (_("hidden"));
  gtk_widget_set_name (hidRow, "hidRow");
  gtk_widget_ref (hidRow);
  gtk_object_set_data_full (GTK_OBJECT (settingseditwin), "hidRow", hidRow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_table_attach (GTK_TABLE (table2), hidRow, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (hidRow), 0, 0.5);

  btnSettingsEditOK = gnome_stock_button (GNOME_STOCK_BUTTON_OK);
  gtk_widget_set_name (btnSettingsEditOK, "btnSettingsEditOK");
  gtk_widget_ref (btnSettingsEditOK);
  gtk_object_set_data_full (GTK_OBJECT (settingseditwin), "btnSettingsEditOK", btnSettingsEditOK,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnSettingsEditOK);
  gtk_box_pack_start (GTK_BOX (vbox7), btnSettingsEditOK, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (settingseditwin), "delete_event",
                      GTK_SIGNAL_FUNC (on_settingseditwin_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnSettingsEditOK), "clicked",
                      GTK_SIGNAL_FUNC (on_btnSettingsEditOK_clicked),
                      NULL);

  gtk_widget_grab_focus (enName);
  return settingseditwin;
}

GtkWidget*
create_debugwin (void)
{
  GtkWidget *debugwin;
  GtkWidget *scrolledwindow4;
  GtkWidget *layout3;
  GtkWidget *lblTiming;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *lblOutput;
  GtkWidget *lblInput;
  GtkWidget *label10;
  GtkWidget *cb1;
  GtkWidget *cb2;
  GtkWidget *cb3;
  GtkWidget *cb4;
  GtkWidget *cb5;
  GtkWidget *cb6;
  GtkWidget *cb7;
  GtkWidget *cb8;
  GtkWidget *tbEnableDebug;
  GtkWidget *tbVrotor;

  debugwin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (debugwin, "debugwin");
  gtk_object_set_data (GTK_OBJECT (debugwin), "debugwin", debugwin);
  gtk_widget_set_usize (debugwin, 365, 165);
  gtk_window_set_title (GTK_WINDOW (debugwin), _("Debug f\366nster"));

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow4, "scrolledwindow4");
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (debugwin), scrolledwindow4);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_NEVER, GTK_POLICY_NEVER);

  layout3 = gtk_layout_new (NULL, NULL);
  gtk_widget_set_name (layout3, "layout3");
  gtk_widget_ref (layout3);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "layout3", layout3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (layout3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), layout3);
  gtk_layout_set_size (GTK_LAYOUT (layout3), 365, 90);
  GTK_ADJUSTMENT (GTK_LAYOUT (layout3)->hadjustment)->step_increment = 10;
  GTK_ADJUSTMENT (GTK_LAYOUT (layout3)->vadjustment)->step_increment = 10;

  lblTiming = gtk_label_new ("");
  gtk_widget_set_name (lblTiming, "lblTiming");
  gtk_widget_ref (lblTiming);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "lblTiming", lblTiming,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblTiming);
  gtk_layout_put (GTK_LAYOUT (layout3), lblTiming, 90, 16);
  gtk_widget_set_usize (lblTiming, 96, 16);
  gtk_label_set_justify (GTK_LABEL (lblTiming), GTK_JUSTIFY_LEFT);

  label23 = gtk_label_new (_("Rotationstid"));
  gtk_widget_set_name (label23, "label23");
  gtk_widget_ref (label23);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label23);
  gtk_layout_put (GTK_LAYOUT (layout3), label23, 0, 15);
  gtk_widget_set_usize (label23, 88, 16);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_LEFT);

  label24 = gtk_label_new (_("Utg\345ngar"));
  gtk_widget_set_name (label24, "label24");
  gtk_widget_ref (label24);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label24);
  gtk_layout_put (GTK_LAYOUT (layout3), label24, 0, 32);
  gtk_widget_set_usize (label24, 88, 16);
  gtk_label_set_justify (GTK_LABEL (label24), GTK_JUSTIFY_LEFT);

  label25 = gtk_label_new (_("Ing\345ngar"));
  gtk_widget_set_name (label25, "label25");
  gtk_widget_ref (label25);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label25);
  gtk_layout_put (GTK_LAYOUT (layout3), label25, 0, 48);
  gtk_widget_set_usize (label25, 88, 16);
  gtk_label_set_justify (GTK_LABEL (label25), GTK_JUSTIFY_LEFT);

  lblOutput = gtk_label_new ("");
  gtk_widget_set_name (lblOutput, "lblOutput");
  gtk_widget_ref (lblOutput);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "lblOutput", lblOutput,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblOutput);
  gtk_layout_put (GTK_LAYOUT (layout3), lblOutput, 90, 32);
  gtk_widget_set_usize (lblOutput, 96, 16);
  gtk_label_set_justify (GTK_LABEL (lblOutput), GTK_JUSTIFY_LEFT);

  lblInput = gtk_label_new ("");
  gtk_widget_set_name (lblInput, "lblInput");
  gtk_widget_ref (lblInput);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "lblInput", lblInput,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lblInput);
  gtk_layout_put (GTK_LAYOUT (layout3), lblInput, 90, 48);
  gtk_widget_set_usize (lblInput, 96, 16);
  gtk_label_set_justify (GTK_LABEL (lblInput), GTK_JUSTIFY_LEFT);

  label10 = gtk_label_new (_("Elevation"));
  gtk_widget_set_name (label10, "label10");
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_layout_put (GTK_LAYOUT (layout3), label10, 195, 8);
  gtk_widget_set_usize (label10, 0, 0);

  cb1 = gtk_check_button_new_with_label (_("Upp"));
  gtk_widget_set_name (cb1, "cb1");
  gtk_widget_ref (cb1);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "cb1", cb1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb1);
  gtk_layout_put (GTK_LAYOUT (layout3), cb1, 256, 8);
  gtk_widget_set_usize (cb1, 48, 16);

  cb2 = gtk_check_button_new_with_label (_("Ner"));
  gtk_widget_set_name (cb2, "cb2");
  gtk_widget_ref (cb2);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "cb2", cb2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb2);
  gtk_layout_put (GTK_LAYOUT (layout3), cb2, 304, 7);
  gtk_widget_set_usize (cb2, 40, 16);

  cb3 = gtk_check_button_new_with_label (_("Skjut"));
  gtk_widget_set_name (cb3, "cb3");
  gtk_widget_ref (cb3);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "cb3", cb3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb3);
  gtk_layout_put (GTK_LAYOUT (layout3), cb3, 192, 24);
  gtk_widget_set_usize (cb3, 64, 16);

  cb4 = gtk_check_button_new_with_label (_("Rotor"));
  gtk_widget_set_name (cb4, "cb4");
  gtk_widget_ref (cb4);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "cb4", cb4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb4);
  gtk_layout_put (GTK_LAYOUT (layout3), cb4, 192, 40);
  gtk_widget_set_usize (cb4, 64, 16);

  cb5 = gtk_check_button_new_with_label (_("Sp\344nnare"));
  gtk_widget_set_name (cb5, "cb5");
  gtk_widget_ref (cb5);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "cb5", cb5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb5);
  gtk_layout_put (GTK_LAYOUT (layout3), cb5, 192, 56);
  gtk_widget_set_usize (cb5, 80, 16);

  cb6 = gtk_check_button_new_with_label (_("Utg\345ng 6"));
  gtk_widget_set_name (cb6, "cb6");
  gtk_widget_ref (cb6);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "cb6", cb6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb6);
  gtk_layout_put (GTK_LAYOUT (layout3), cb6, 192, 72);
  gtk_widget_set_usize (cb6, 72, 16);

  cb7 = gtk_check_button_new_with_label (_("Utg\345ng 7"));
  gtk_widget_set_name (cb7, "cb7");
  gtk_widget_ref (cb7);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "cb7", cb7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb7);
  gtk_layout_put (GTK_LAYOUT (layout3), cb7, 192, 88);
  gtk_widget_set_usize (cb7, 72, 16);

  cb8 = gtk_check_button_new_with_label (_("Utg\345ng 8"));
  gtk_widget_set_name (cb8, "cb8");
  gtk_widget_ref (cb8);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "cb8", cb8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb8);
  gtk_layout_put (GTK_LAYOUT (layout3), cb8, 192, 104);
  gtk_widget_set_usize (cb8, 72, 16);

  tbEnableDebug = gtk_toggle_button_new_with_label (_("S\344tt debug flagga"));
  gtk_widget_set_name (tbEnableDebug, "tbEnableDebug");
  gtk_widget_ref (tbEnableDebug);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "tbEnableDebug", tbEnableDebug,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tbEnableDebug);
  gtk_layout_put (GTK_LAYOUT (layout3), tbEnableDebug, 8, 100);
  gtk_widget_set_usize (tbEnableDebug, 108, 24);

  tbVrotor = gtk_toggle_button_new_with_label (_("Simluera rotor"));
  gtk_widget_set_name (tbVrotor, "tbVrotor");
  gtk_widget_ref (tbVrotor);
  gtk_object_set_data_full (GTK_OBJECT (debugwin), "tbVrotor", tbVrotor,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tbVrotor);
  gtk_layout_put (GTK_LAYOUT (layout3), tbVrotor, 8, 128);
  gtk_widget_set_usize (tbVrotor, 108, 24);

  gtk_signal_connect (GTK_OBJECT (debugwin), "delete_event",
                      GTK_SIGNAL_FUNC (on_debugwin_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cb1), "toggled",
                      GTK_SIGNAL_FUNC (on_cb_manual_toggled),
                      (gpointer)0x01);
  gtk_signal_connect (GTK_OBJECT (cb2), "toggled",
                      GTK_SIGNAL_FUNC (on_cb_manual_toggled),
                      (gpointer)0x02);
  gtk_signal_connect (GTK_OBJECT (cb3), "toggled",
                      GTK_SIGNAL_FUNC (on_cb_manual_toggled),
                      (gpointer)0x4);
  gtk_signal_connect (GTK_OBJECT (cb4), "toggled",
                      GTK_SIGNAL_FUNC (on_cb_manual_toggled),
                      (gpointer)0x8);
  gtk_signal_connect (GTK_OBJECT (cb5), "toggled",
                      GTK_SIGNAL_FUNC (on_cb_manual_toggled),
                      (gpointer)0x10);
  gtk_signal_connect (GTK_OBJECT (cb6), "toggled",
                      GTK_SIGNAL_FUNC (on_cb_manual_toggled),
                      (gpointer)0x20);
  gtk_signal_connect (GTK_OBJECT (cb7), "toggled",
                      GTK_SIGNAL_FUNC (on_cb_manual_toggled),
                      (gpointer)0x40);
  gtk_signal_connect (GTK_OBJECT (cb8), "toggled",
                      GTK_SIGNAL_FUNC (on_cb_manual_toggled),
                      (gpointer)0x80);
  gtk_signal_connect (GTK_OBJECT (tbEnableDebug), "toggled",
                      GTK_SIGNAL_FUNC (on_tbEnableDebug_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (tbVrotor), "toggled",
                      GTK_SIGNAL_FUNC (on_tbVrotor_toggled),
                      NULL);

  gtk_widget_grab_focus (tbEnableDebug);
  return debugwin;
}

GtkWidget*
create_dlgWarnReset (void)
{
  GtkWidget *dlgWarnReset;
  GtkWidget *dialog_vbox2;
  GtkWidget *label46;
  GtkWidget *dialog_action_area2;
  GtkWidget *btnWarnReset;

  dlgWarnReset = gtk_dialog_new ();
  gtk_widget_set_name (dlgWarnReset, "dlgWarnReset");
  gtk_object_set_data (GTK_OBJECT (dlgWarnReset), "dlgWarnReset", dlgWarnReset);
  gtk_widget_set_usize (dlgWarnReset, 245, 255);
  gtk_window_set_title (GTK_WINDOW (dlgWarnReset), _("- VARNING -"));
  gtk_window_set_position (GTK_WINDOW (dlgWarnReset), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (dlgWarnReset), TRUE);
  gtk_window_set_policy (GTK_WINDOW (dlgWarnReset), TRUE, TRUE, FALSE);

  dialog_vbox2 = GTK_DIALOG (dlgWarnReset)->vbox;
  gtk_widget_set_name (dialog_vbox2, "dialog_vbox2");
  gtk_object_set_data (GTK_OBJECT (dlgWarnReset), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);

  label46 = gtk_label_new (_("\nVARNING\n\nAlla utg\345ngar \344r ej nollst\344llda.\nProgrammet kommer att nollst\344lla\ndem n\344r du trycker OK.\n\nSe till att rotorn \344r upphissad innan\ndu trycker OK, ifall sp\344nnaren sl\344pper.\n\nOm sp\344nnaren sl\344pperkommer \nen lerduva att kastas iv\344g."));
  gtk_widget_set_name (label46, "label46");
  gtk_widget_ref (label46);
  gtk_object_set_data_full (GTK_OBJECT (dlgWarnReset), "label46", label46,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), label46, FALSE, FALSE, 0);

  dialog_action_area2 = GTK_DIALOG (dlgWarnReset)->action_area;
  gtk_widget_set_name (dialog_action_area2, "dialog_action_area2");
  gtk_object_set_data (GTK_OBJECT (dlgWarnReset), "dialog_action_area2", dialog_action_area2);
  gtk_widget_show (dialog_action_area2);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area2), 10);

  btnWarnReset = gnome_stock_button (GNOME_STOCK_BUTTON_OK);
  gtk_widget_set_name (btnWarnReset, "btnWarnReset");
  gtk_widget_ref (btnWarnReset);
  gtk_object_set_data_full (GTK_OBJECT (dlgWarnReset), "btnWarnReset", btnWarnReset,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnWarnReset);
  gtk_box_pack_start (GTK_BOX (dialog_action_area2), btnWarnReset, TRUE, TRUE, 0);
  gtk_widget_set_usize (btnWarnReset, -2, 34);

  gtk_signal_connect (GTK_OBJECT (dlgWarnReset), "destroy_event",
                      GTK_SIGNAL_FUNC (on_dlgWarnReset_destroy_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnWarnReset), "clicked",
                      GTK_SIGNAL_FUNC (on_btnWarnReset_clicked),
                      NULL);

  return dlgWarnReset;
}

