/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>

#include "interface.h"
#include "support.h"

GtkWidget *mainwin;
GtkWidget *sbStatus;
GtkWidget *tbRotor;
GtkWidget *tbProgrun;
GtkWidget *btnProgreset;
int adlink_fd;

int
main (int argc, char *argv[])
{

  gnome_init ("slim", VERSION, argc, argv);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  mainwin = create_mainwin ();
  gtk_widget_show (mainwin);

  sbStatus = lookup_widget(mainwin, "sbStatus");
  tbRotor = lookup_widget(mainwin, "tbRotor");
  tbProgrun = lookup_widget(mainwin, "tbProgrun");
  btnProgreset = lookup_widget(mainwin, "btnProgreset");

  gtk_main ();
  return 0;
}

